version: '3.9'

services:
  app:
    build: .
    restart: unless-stopped
    hostname: client
    ports:
      - "3000:3000"
    networks:
      - client
      - gateway

networks:
  client:
    driver: bridge

  gateway:
    driver: bridge
    external: true
