version: '3.8'

services:
  # The client application container
  client-app:
    build:
      context: ./.docker/dev/app
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      # Direct Nuxt port
      - "3000:3000"
      # Nuxt dev WebSocket port
      - "24678:24678"
    networks:
      - client
      - api

networks:
  client:
    driver: bridge

  api:
    external:
      name: api_network
