name: api-local

version: '3.9'

services:
  web:
    build:
      context: .
      target: web
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - ./:/app
    working_dir: /app
    restart: unless-stopped
    command: php artisan octane:start --server=swoole --host=0.0.0.0 --port=8000 --watch
    ports:
      - "8000:8000"

  schedule:
    build:
      context: .
      target: cli
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - ./:/app
    working_dir: /app
    restart: unless-stopped
    command: php artisan schedule:work

  queue:
    build:
      context: .
      target: cli
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - ./:/app
    working_dir: /app
    restart: unless-stopped
    command: php artisan queue:work --tries=3

  postgres:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2-alpine
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

  mailpit:
    image: axllent/mailpit:latest
    volumes:
      - mailpit:/data
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/buckets
    environment:
      MINIO_ROOT_USER: minio-user
      MINIO_ROOT_PASSWORD: minio-password
    command: server /buckets --console-address ":9001"

volumes:
  postgres:
    driver: local
  redis:
    driver: local
  mailpit:
    driver: local
  minio:
    driver: local
