name: api-testing

version: '3.9'

services:
  app:
    build:
      context: .
      target: dev
    environment:
      APP_ENV: testing
    depends_on:
      - pgsql
    volumes:
      - ./:/app
    working_dir: /app

  pgsql:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
