name: api-testing

version: '3.9'

services:
  cli:
    build:
      context: .
      target: dev
    environment:
      APP_NAME: Laravel
      APP_ENV: testing
      APP_KEY: base64:YATW8fOGnL4XznjcaIloh9e4ub9N9IAeb+Gz8tyfzC0=
      APP_DEBUG: true
      APP_URL: http://localhost:8000

      LOG_CHANNEL: stderr
      LOG_DEPRECATIONS_CHANNEL: stderr
      LOG_LEVEL: debug

      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: app
      DB_USERNAME: app
      DB_PASSWORD: app

      BCRYPT_ROUNDS: 4
      BROADCAST_DRIVER: log
      CACHE_DRIVER: array
      FILESYSTEM_DISK: local
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: array
      MAIL_MAILER: array

      PULSE_ENABLED: false
      TELESCOPE_ENABLED: false
    depends_on:
      - postgres
    volumes:
      - ./:/app
    working_dir: /app

  postgres:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
