version: '3.9'

services:
  console:
    build: .
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:YATW8fOGnL4XznjcaIloh9e4ub9N9IAeb+Gz8tyfzC0=
      APP_DEBUG: true
      APP_URL: http://localhost:8000

      LOG_CHANNEL: stderr
      LOG_DEPRECATIONS_CHANNEL: stderr
      LOG_LEVEL: debug

      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: app
      DB_USERNAME: app
      DB_PASSWORD: app

      BROADCAST_DRIVER: redis
      CACHE_DRIVER: redis
      FILESYSTEM_DISK: local
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis
      SESSION_LIFETIME: 120

      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379

      MAIL_MAILER: smtp
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
      MAIL_FROM_ADDRESS: "hello@example.com"
      MAIL_FROM_NAME: Laravel
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - ./:/app
    working_dir: /app
    restart: unless-stopped
    command: php artisan schedule:work

  web:
    extends:
      service: console
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000

  queue:
    extends:
      service: console
    command: php artisan queue:work --tries=3

  postgres:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2-alpine
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

  mailpit:
    image: axllent/mailpit:latest
    volumes:
      - mailpit:/data
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  postgres:
    driver: local
  redis:
    driver: local
  mailpit:
    driver: local
