name: api-testing

version: '3.9'

services:
    app:
        build:
            context: .
            target: base-dev
        environment:
            APP_ENV: testing
            XDEBUG_MODE: ${XDEBUG_MODE:-off}
        extra_hosts:
            - host.docker.internal:host-gateway
        depends_on:
            - pgsql
        volumes:
            - .:/app
        working_dir: /app

    pgsql:
        image: postgres:16.1-alpine
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: app
            POSTGRES_PASSWORD: app
