name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: app
          POSTGRES_DB: app
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.3'
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('api/.env') || copy('api/.env.example', 'api/.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      working-directory: api
    - name: Generate key
      run: php artisan key:generate
      working-directory: api
    - name: Directory Permissions
      run: chmod -R 777 api/storage api/bootstrap/cache
    - name: Create Database
      run: |
        php -r "file_exists('api/.env') || copy('api/.env.example', 'api/.env');"
        php artisan migrate --force
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        APP_ENV: ${{ secrets.APP_ENV }}
        APP_DEBUG: ${{ secrets.APP_DEBUG }}
        APP_URL: ${{ secrets.APP_URL }}
        DB_CONNECTION: pgsql
        DB_HOST: localhost
        DB_PORT: 5432
        DB_DATABASE: app
        DB_USERNAME: app
        DB_PASSWORD: app
      run: php artisan test
      working-directory: api
