name: Run Tests

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main
      - dev

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Start Docker Compose
      run: docker-compose -f web/compose.testing.yaml up -d

    - name: Execute Tests
      run: docker-compose -f web/compose.testing.yaml exec app vendor/bin/phpunit

    - name: Stop Docker Compose
      run: docker-compose -f web/compose.testing.yaml down